CONTRIBUTING.md, Makefile, README.md, docker/social-ui-dev/docker-compose.yml, docker/social-ui-prod/docker-compose.yml, package.json, src/i18n/locales/en.json
Replaces all references to [social-ui](https://github.com/forrestwilkins/social-ui) with [praxis-ui](https://github.com/praxis-project/praxis-ui) name.
=> Replace references to social-ui with praxis-ui

src/components/About/WelcomeCard.tsx, src/i18n/locales/en.json, src/pages/index.tsx
Adds a welcome message card to greet users with project description on home page and sign up.
=> Add welcome message

next.config.js, src/apollo/cache.ts, src/components/About/WelcomeCard.tsx, src/components/Navigation/NavDrawer.tsx, src/components/Navigation/TopNavDesktop.tsx, src/constants/common.constants.ts, src/constants/server-invite.constants.ts, src/pages/auth/signup.tsx, src/pages/invites/[token].tsx, src/utils/common.utils.ts
Invite links take the user an invite page with a welcome message and a link to sign up.
=> Add server invite page

schema.graphql, src/apollo/gen.ts, src/constants/user.constants.ts, src/i18n/locales/en.json, src/pages/auth/signup.tsx
Adds a "Confirm Password" field to the sign up form, along with some basic validation.
Related PR: https://github.com/praxis-project/praxis-api/pull/110
=> Add confirm password field to sign up form

schema.graphql, src/apollo/gen.ts, src/components/About/WelcomeCard.tsx, src/i18n/locales/en.json, src/pages/auth/signup.tsx
Enables users to upload a profile picture on sign up.
Related PR: https://github.com/praxis-project/praxis-api/pull/111
=> Upload profile picture on sign up

src/components/Groups/GroupForm.tsx, src/components/Posts/PostForm.tsx, src/components/Proposals/ProposalForm.tsx, src/components/Roles/RoleForm.tsx, src/components/ServerInvites/ServerInviteForm.tsx, src/components/Shared/PrimaryActionButton.tsx, src/components/Users/EditProfileForm.tsx, src/pages/auth/login.tsx, src/pages/auth/signup.tsx
Adds a spinner to show loading state for submit buttons in forms.
=> Add loading state for submit buttons

src/components/Navigation/TopNavDesktop.tsx, src/components/Shared/SearchBar.tsx, src/pages/groups/index.tsx
Resolves any blinking issues for the top navigational component on desktop.
=> Fix top nav blinking issue

src/i18n/locales/en.json, src/pages/events/index.tsx, src/pages/groups/index.tsx, src/utils/common.utils.ts
Adds a short message to the events page explaining how events can be useful and how the feature is still in development.
Message:
> Plan Events
>
> Events are a powerful tool for bringing people together and building momentum for a cause. Whether you're organizing a fundraiser or a simple a meet and greet, events can help you connect with like-minded individuals in your community and make a positive impact.
>
> This feature is still in development.
=> Add "Plan Events" message to events page

src/i18n/locales/en.json, src/pages/events/index.tsx, src/pages/groups/index.tsx
Updates the messages shown on events and groups pages when the user is logged out. Ensures that they're better differentiated and that both make mention of proposals.
=> Update groups and events messages

schema.graphql, src/apollo/gen.ts, src/apollo/users/fragments/Follow.fragment.graphql, src/apollo/users/fragments/FollowedUser.fragment.graphql, src/apollo/users/fragments/Follower.fragment.graphql, src/apollo/users/mutations/FollowUser.mutation.graphql, src/apollo/users/queries/Followers.query.graphql, src/apollo/users/queries/Following.query.graphql, src/components/Users/Follow.tsx, src/pages/users/[name]/followers.tsx, src/pages/users/[name]/following.tsx
Updates components, follow queries, and other documents to match schema changes.
BE PR: https://github.com/praxis-app/praxis-api/pull/114
=> Followers refactor

src/apollo/gen.ts, src/apollo/invites/fragments/ServerInviteCard.fragment.graphql, src/apollo/invites/mutations/CreateServerInvite.mutation.graphql, src/apollo/invites/queries/ServerInvites.query.graphql, src/components/ServerInvites/ServerInviteCard.tsx, src/components/ServerInvites/ServerInviteRow.tsx, src/components/ServerInvites/ServerInviteTable.tsx, src/constants/common.constants.ts, src/i18n/locales/en.json, src/pages/invites/index.tsx, src/utils/server-invite.utils.ts
Adds improved UI for server invites on mobile. Desktop still shows a table view, while mobile lists invites as cards.
=> Server invites mobile layout

README.md
Adds invite link to discord server along with instructions to request link to Notion page.
=> Add invite link for Discord server to readme

codegen.ts, schema.graphql, src/apollo/cache.ts, src/apollo/gen.ts, src/apollo/groups/queries/MemberRequests.query.graphql, src/components/Groups/GroupCard.tsx, src/components/Groups/GroupProfileCard.tsx, src/components/Groups/JoinButton.tsx, src/components/Groups/RequestToJoin.tsx, src/pages/groups/[name].tsx, src/pages/groups/[name]/requests.tsx, src/pages/groups/index.tsx
Includes changes that depend on new shield rules added to API in PR linked below.
Related PR: https://github.com/praxis-app/praxis-api/pull/120
=> Group roles - New rules

schema.graphql, src/apollo/gen.ts, src/apollo/groups/fragments/CurrentMember.fragment.graphql, src/apollo/groups/fragments/GroupCard.fragment.graphql, src/apollo/groups/fragments/GroupMember.fragment.graphql, src/apollo/groups/fragments/GroupProfileCard.fragment.graphql, src/apollo/groups/mutations/ApproveMemberRequest.mutation.graphql, src/apollo/groups/mutations/CreateGroup.mutation.graphql, src/components/Groups/GroupCard.tsx, src/components/Groups/GroupMember.tsx, src/components/Groups/GroupProfileCard.tsx, src/components/Groups/JoinButton.tsx, src/pages/groups/[name].tsx
Removes all references to `GroupMember` type in accordance with removal of type from API.
Depends on:  https://github.com/praxis-app/praxis-api/pull/121
=> Refactor group member relations

src/components/Proposals/ProposeRoleMemberOption.tsx, src/components/Proposals/ProposeRoleModal.tsx, src/components/Roles/AddRoleMemberOption.tsx, src/components/Roles/AddRoleMemberTab.tsx, src/components/Roles/RoleMemberOption.tsx, src/constants/role.constants.ts
Refactors how state is handled on the FE for proposed changes to role members.
Merges into: https://github.com/praxis-app/praxis-ui/pull/31
=> Proposed role member refactor

src/components/Auth/__tests__/SignupForm.test.tsx
have added unit test for sign up form
=> add unit test for sign up form

src/components/Auth/__tests__/LoginForm.test.tsx, src/components/Auth/__tests__/SignupForm.test.tsx
Makes come small clean up changes for unit tests.
=> Clean up auth form unit tests

package.json, src/apollo/gen.ts, src/apollo/groups/fragments/GroupCard.fragment.graphql, src/apollo/groups/fragments/GroupProfileCard.fragment.graphql, src/apollo/groups/mutations/UpdateGroupSettings.mutation.graphql, src/apollo/groups/queries/GroupProfile.query.graphql, src/apollo/groups/queries/Groups.query.graphql, src/apollo/groups/queries/PublicGroups.query.graphql, src/apollo/groups/queries/PublicGroupsFeed.query.graphql, src/apollo/posts/fragments/PostCard.fragment.graphql, src/apollo/posts/fragments/PostCardFooter.fragment.graphql, src/apollo/posts/mutations/CreatePost.mutation.graphql, src/apollo/posts/mutations/LikePost.mutation.graphql, src/apollo/posts/mutations/UpdatePost.mutation.graphql, src/apollo/posts/queries/Post.query.graphql, src/apollo/proposals/fragments/ProposalCardFooter.fragment.graphql, src/apollo/proposals/mutations/CreateProposal.mutation.graphql, src/apollo/proposals/mutations/UpdateProposal.mutation.graphql, src/apollo/proposals/queries/Proposal.query.graphql, src/apollo/users/mutations/FollowUser.mutation.graphql, src/apollo/users/queries/EditUser.query.graphql, src/apollo/users/queries/HomeFeed.query.graphql, src/apollo/users/queries/UserProfile.query.graphql, src/components/Posts/PostCard.tsx, src/components/Proposals/ProposalCard.tsx, src/pages/groups/[name].tsx, src/pages/posts/[id].tsx, src/pages/proposals/[id].tsx, src/pages/users/[name].tsx
Adds `@include` directives for any fields that can only be accessed when logged in.
This reduces `Unauthorized` errors and ensures we only hit the resolvers that are needed.
Merges into: https://github.com/praxis-app/praxis-ui/pull/52
=> Add include directives for protected fields

src/components/Proposals/ProposalActionRole.tsx
Ensures that color changes are also flush and left aligned with other changes in proposed role cards on mobile.
=> Left align color changes in proposed role card

src/components/Shared/ToggleForms.tsx, src/styles/theme.ts
Updates appearance for toggle buttons used to switch between post and proposal form.
Improves color contrast between button icons and background.
=> Improve post / proposal toggle buttons

.eslintrc, src/components/Docs/DocsDefinitionListItem.tsx, src/components/Docs/DocsPermissionList.tsx, src/pages/docs/index.tsx
Adds a brief explanation of voting, model of consensus, and the different vote types available to users.
=> Add explanation of voting and consensus to docs

schema.graphql, src/apollo/events/fragments/EventAvatar.fragment.graphql, src/apollo/events/fragments/EventForm.fragment.graphql, src/apollo/events/fragments/EventPageCard.fragment.graphql, src/apollo/gen.ts, src/apollo/groups/queries/GroupEventsTab.query.graphql, src/apollo/posts/fragments/PostCard.fragment.graphql, src/apollo/proposals/fragments/ProposalAction.fragment.graphql, src/apollo/proposals/fragments/ProposalActionEvent.fragment.graphql, src/apollo/proposals/fragments/ProposalActionEventAvatar.fragment.graphql, src/apollo/users/queries/UserByUserId.query.graphql, src/components/Events/EventAvatar.tsx, src/components/Events/EventForm.tsx, src/components/Events/EventItemAvatar.tsx, src/components/Events/EventPageCard.tsx, src/components/Groups/GroupEventsTab.tsx, src/components/Proposals/ProposalActions/ProposalAction.tsx, src/components/Proposals/ProposalActions/ProposalActionEvent.tsx, src/components/Proposals/ProposalActions/ProposalActionRole.tsx, src/components/Proposals/ProposalActions/ProposeEventModal.tsx, src/components/Proposals/ProposalCard.tsx, src/components/Proposals/ProposalForm.tsx, src/components/Shared/ToggleForms.tsx, src/constants/proposal.constants.ts, src/i18n/locales/en.json, src/utils/common.utils.ts, src/utils/proposal.utils.ts
Adds basic functionality for proposals to plan group events.
Depends on: https://github.com/praxis-app/praxis-api/pull/151
Closes: https://github.com/praxis-app/praxis-ui/issues/40
=> Proposals to plan events
